name: "Maintenance"
description: "メンテナンス・リファクタリングタスク"
title: "[Chore] "
labels: ["maintenance"]
body:
  - type: textarea
    id: task
    attributes:
      label: "タスク内容"
      description: "何をしたいか簡潔に"
      placeholder: "例: Dependabotの未対応PRを整理したい"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: "種類"
      options:
        - "依存関係の更新"
        - "リファクタリング"
        - "CI/CD改善"
        - "ドキュメント"
        - "テスト追加"
        - "セキュリティ対応"
        - "その他"
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: "補足（任意）"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Claude Code でタスクを実行する方法（GitHub Mobileアプリ内で完結）:**

        1. **ラベルで起動（タイピング不要）** — `approved` ラベルを付ける → 自動作業開始
        2. **Actionsタブで起動** — Actions → Claude Code → Run workflow → プロンプト入力
        3. **コメントで起動** — `@claude [指示内容]` と書く（iOSでは `@Claude` でもOK）
